version = 0.1
[default.deploy.parameters]
stack_name = "co-apt-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yw7ujcmlls1t"
s3_prefix = "co-apt-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []

[default.build.parameters]
template_file = "template.yml"
cached = true
parallel = true
use_container = true